1. X variables - Birth to BWT
2. Paayos ng output for predictions
3. Lagyan ng header/markdown description ng code
4. Feature importance plot
5. plot for accuracy vs diff. n_estimators

In [1]:
# Import required modules
import pandas as pd
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import cross_val_score
from sklearn.model_selection import train_test_split

C:\Users\trixie.deguzman\AppData\Local\Anaconda2\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
# Import data
data = pd.read_csv('lowdata.csv')
data.head()

   ID  BIRTH  SMOKE  RACE  AGE  LWT   BWT  LOW
0   1      1      1     3   28  120  2865    1
1   2      2      1     3   33  141  2609    0
2   3      1      0     1   29  130  2613    1
3   4      2      0     1   34  151  3125    0
4   5      3      0     1   37  144  2481    1

In [4]:
# The data have to be in a numpy array in order for the random forest algorithm to accept it
# Splitting train and test data
x_data = data.iloc[:, :-1].values
y_data = data.iloc[:, -1].values

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, random_state=0)

In [5]:
rf = RandomForestClassifier(n_estimators=100, random_state=0) # initialize
rf.fit(x_train, y_train) # fit the data to the algorithm

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [6]:
results = rf.predict(x_test)

In [7]:
results

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0], dtype=int64)

In [8]:
test = pd.DataFrame(x_test, columns = ['ID', 'BIRTH', 'SMOKE', 'RACE', 'AGE', 'LWT', 'BWT'])

In [9]:
test['predictions'] = results

In [10]:
test

      ID  BIRTH  SMOKE  RACE  AGE  LWT   BWT  predictions
0     16      1      0     3   23   97  3138            0
1    251      2      1     1   24  166  2457            1
2    143      2      1     3   17  117  3842            1
3    356      2      0     2   21  245  2707            0
4     91      3      1     2   22  124  2524            1
5    419      2      0     1   29  141  2345            1
6    145      1      1     1   28   95  2213            1
7    348      1      0     2   16  112  3226            1
8     97      2      0     3   31  113  2491            1
9     22      1      0     3   24  132  3158            0
10   362      1      1     2   20  121  3184            0
11   409      2      0     1   33  176  4005            0
12   312      2      0     3   23  126  3019            0
13   395      2      0     1   30  168  2446            1
14   101      2      0     1   18  125  2200            1
15   135      2      0     3   29  171  3541            0
16    77      2      1     3   24  103  1308            1
17   160      2      0     3   32  169  3336            0
18   206      1      1     1   28  120  3623            0
19   187      2      0     3   26  114  3057            0
20   255      2      1     1   32  230  3538            0
21   195      1      1     1   18  100  3010            1
22   484      2      1     1   25  152  3006            0
23    38      3      1     1   34  121  2607            0
24   482      3      0     1   39  191  3086            0
25   273      3      1     1   25  112  1456            1
26   250      1      1     1   19  138  2591            0
27   197      3      1     1   29  134  2451            1
28   346      2      1     3   28  141  2310            1
29   410      3      0     1   37  171  4049            0
..   ...    ...    ...   ...  ...  ...   ...          ...
92   440      4      0     2   32  202  2879            0
93   423      2      0     3   27  126  2525            0
94   247      2      0     2   27  145  2769            0
95   301      3      0     3   27  131  2954            0
96   485      3      1     1   27  128  2237            1
97   172      1      0     3   17  103  2592            1
98   447      3      1     1   37  169  2499            1
99   457      2      0     1   19  160  2562            0
100  386      2      0     1   28  153  4016            0
101  361      2      1     1   34  158  2346            1
102  222      2      0     3   27  136  3284            0
103   60      3      1     1   27  126  1826            1
104  378      3      0     3   32  142  4242            0
105  382      1      0     3   19  105  2148            1
106  155      2      1     1   27  155  2801            0
107  463      1      0     3   16   95  3297            1
108  474      2      0     1   28  161  1998            1
109   66      1      1     3   17  130  3397            1
110  296      1      1     1   30   95  2001            1
111   46      2      1     1   30  177  1943            1
112  300      2      0     3   23  122  3342            0
113   56      2      0     1   24  130  3775            0
114  180      3      1     1   37  147  3412            0
115  413      3      1     1   26  161  2780            0
116  402      2      1     1   31  134  3245            0
117  436      2      1     1   20  128  2813            0
118  125      3      1     1   30  142  2312            1
119  226      2      0     1   32  190  2034            1
120  192      1      1     1   18  100  2665            1
121  358      2      0     1   29  163  2769            0

[122 rows x 8 columns]

In [11]:
rf.score(x_test,y_test)

0.9508196721311475

In [12]:
rf3 = RandomForestClassifier(n_estimators=1, random_state=0) # initialize
rf3.fit(x_train, y_train) # fit the data to the algorithm

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [13]:
rf3.score(x_test,y_test)

0.9098360655737705